# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.data.meta.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aensidhe.ru" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

sass:
  sass_dir: _sass
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - so-simple-theme-master
  - .vscode
  - sitemap.xml
  - robots.txt
include:
  - _pages

# Polyglot
languages: ["ru", "en"]
default_lang: "ru"
exclude_from_localization: ["assets", "images", "so-simple-theme-master"]
parallel_localization: true

# Site owner
owner:
  name: Anatoly 'Aen Sidhe' Popov
  avatar: aen.jpg
  email: me@aensidhe.ru
  disqus-shortname: aensidhe
  twitter: aensidhe #username
  facebook: aensidhe #username
  github: aensidhe #username
  stackexchange: https://stackoverflow.com/users/27337/aen-sidhe
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: aensidhe #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  yandex:
    metrica: 46449744